### ISSUE TITLE
HTTPClient.session.verify not working

### ISSUE THREAD

**Issue by luzik** [bcb/jsonrpcclient#65]
```
$ python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> requests.get('https://192.168.40.104/rpc/', verify='2_cert.pem')
/home/luzik/.local/lib/python3.5/site-packages/urllib3/connection.py:344: SubjectAltNameWarning: Certificate for 192.168.40.104 has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SubjectAltNameWarning
<Response [200]>
>>> from jsonrpcclient.http_client import HTTPClient
>>> client = HTTPClient('https://192.168.40.104/rpc/')
>>> client.session.verify
True
>>> client.session.verify = '2_cert.pem'
>>> client.session.verify
'2_cert.pem'
>>> client.request('cat')
--> {"id": 1, "method": "cat", "jsonrpc": "2.0"}
Traceback (most recent call last):
  File "/home/luzik/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/luzik/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/home/luzik/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/home/luzik/.local/lib/python3.5/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/home/luzik/.local/lib/python3.5/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 377, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 752, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/luzik/.local/lib/python3.5/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/luzik/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/luzik/.local/lib/python3.5/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='192.168.40.104', port=443): Max retries exceeded with url: /rpc/ (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/luzik/.local/lib/python3.5/site-packages/jsonrpcclient/client.py", line 200, in request
    return self.send(Request(method_name, *args, **kwargs))
  File "/home/luzik/.local/lib/python3.5/site-packages/jsonrpcclient/client.py", line 171, in send
    return self._send_message(request, **kwargs)
  File "/home/luzik/.local/lib/python3.5/site-packages/jsonrpcclient/http_client.py", line 75, in _send_message
    cert=cert, proxies=proxies)
  File "/home/luzik/.local/lib/python3.5/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/luzik/.local/lib/python3.5/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='192.168.40.104', port=443): Max retries exceeded with url: /rpc/ (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)'),))
>>> client.session.verify = False
>>> client.request('cat')
--> {"id": 2, "method": "cat", "jsonrpc": "2.0"}
Traceback (most recent call last):
  File "/home/luzik/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/luzik/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/home/luzik/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/home/luzik/.local/lib/python3.5/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/home/luzik/.local/lib/python3.5/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 377, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 752, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 988, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 633, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/luzik/.local/lib/python3.5/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/luzik/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/luzik/.local/lib/python3.5/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='192.168.40.104', port=443): Max retries exceeded with url: /rpc/ (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/luzik/.local/lib/python3.5/site-packages/jsonrpcclient/client.py", line 200, in request
    return self.send(Request(method_name, *args, **kwargs))
  File "/home/luzik/.local/lib/python3.5/site-packages/jsonrpcclient/client.py", line 171, in send
    return self._send_message(request, **kwargs)
  File "/home/luzik/.local/lib/python3.5/site-packages/jsonrpcclient/http_client.py", line 75, in _send_message
    cert=cert, proxies=proxies)
  File "/home/luzik/.local/lib/python3.5/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/luzik/.local/lib/python3.5/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='192.168.40.104', port=443): Max retries exceeded with url: /rpc/ (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)'),))
>>> 

```

**Comment by bcb** [comment]
Thanks for reporting.

I believe I've fixed the issue. Please try using the master branch from github.

**Comment by luzik** [comment]
It doesn't. You can check on any site with wrong cert
For example a random site (with another SSL error)
```
$ python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from jsonrpcclient.http_client import HTTPClient
>>> client = HTTPClient('https://lyzkikoparkowe.com.pl/')
>>> client.session.verify = False
>>> client.request('cat')
--> {"method": "cat", "id": 1, "jsonrpc": "2.0"}
Traceback (most recent call last):
```

**Comment by luzik** [comment]
My fix is ok, but there is another issue: whenever change client.session.verify to something correct ..like False or path to proper cert file, it stick to it, and changing client.session.verify to True or bad cert still gives positives verify results :-/ .But i think this is strictly related to requests module

client = HTTPClient('https://lyzkikoparkowe.com.pl/')
client.request('cat') - FAIL
client.session.verify = False
client.request('cat') - OK
client.session.verify = True
client.request('cat') - OK
client = HTTPClient('https://192.168.40.104/rpc')
client.request('cat') - FAIL
client.session.verify = 'bad_cert'
client.request('cat') - FAIL
client.session.verify = 'bad_cert2'
client.request('cat') - FAIL
client.session.verify = 'good_cert'
client.request('cat') - OK
client.session.verify = 'bad_cert2'
client.request('cat') - OK
client.session.verify = 'bad_cert'
client.request('cat') - OK

**Comment by bcb** [comment]
Ok, try now.

It's no longer passing specific params to `requests.Request` or `Session.send`.

**Comment by luzik** [comment]
>>> client.send(Request('cat'), cert=('3_cert.pem', '3_key.pem'), verify='2_cert.pem')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/luzik/.local/lib/python3.5/site-packages/jsonrpcclient/client.py", line 166, in send
    self.prepare_request(request, **kwargs)
  File "/home/luzik/.local/lib/python3.5/site-packages/jsonrpcclient/http_client.py", line 47, in prepare_request
    req = Request(method='POST', url=self.endpoint, data=request, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'cert'

**Comment by bcb** [comment]
```python
>>> from jsonrpcclient.http_client import HTTPClient
>>> client = HTTPClient('http://localhost:5000')
>>> client.request('ping')
--> {"jsonrpc": "2.0", "method": "ping", "id": 1}
<-- {"jsonrpc": "2.0", "result": "pong", "id": 1} (200 OK)
'pong'
>>> client.session.cert = 'nonexistant'
>>> client.request('ping')
--> {"jsonrpc": "2.0", "method": "ping", "id": 2}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/beau/personal/jsonrpcclient/jsonrpcclient/client.py", line 200, in request
    return self.send(Request(method_name, *args, **kwargs))
  File "/Users/beau/personal/jsonrpcclient/jsonrpcclient/client.py", line 171, in send
    return self.send_message(request, **kwargs)
  File "/Users/beau/personal/jsonrpcclient/jsonrpcclient/http_client.py", line 69, in send_message
    response = self.session.send(request.prepped, **kwargs)
  File "/Users/beau/.virtualenvs/jsonrpcclient/lib/python3.6/site-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/Users/beau/.virtualenvs/jsonrpcclient/lib/python3.6/site-packages/requests/adapters.py", line 407, in send
    self.cert_verify(conn, request.url, verify, cert)
  File "/Users/beau/.virtualenvs/jsonrpcclient/lib/python3.6/site-packages/requests/adapters.py", line 248, in cert_verify
    "invalid path: {0}".format(conn.cert_file))
OSError: Could not find the TLS certificate file, invalid path: nonexistant
>>> client.session.cert = None
>>> client.request('ping')
--> {"jsonrpc": "2.0", "method": "ping", "id": 3}
<-- {"jsonrpc": "2.0", "result": "pong", "id": 3} (200 OK)
'pong'
```

**Comment by bcb** [comment]
The params passed to "send" are passed through to requests.Request, which doesn't accept "cert"
http://docs.python-requests.org/en/master/api/#requests.Request

**Comment by bcb** [comment]
If you pull now, you can also use pass the cert with `send`.

```python
>>> from jsonrpcclient.http_client import HTTPClient
>>> client = HTTPClient('http://localhost:5000')
>>> client.request('ping')
--> {"jsonrpc": "2.0", "method": "ping", "id": 1}
<-- {"jsonrpc": "2.0", "result": "pong", "id": 1} (200 OK)
'pong'
>>> from jsonrpcclient.request import Request
>>> client.send(Request('ping'), cert='nonexistant')
--> {"jsonrpc": "2.0", "method": "ping", "id": 3}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/beau/personal/jsonrpcclient/jsonrpcclient/client.py", line 171, in send
    return self.send_message(request, **kwargs)
  File "/Users/beau/personal/jsonrpcclient/jsonrpcclient/http_client.py", line 69, in send_message
    response = self.session.send(request.prepped, **kwargs)
  File "/Users/beau/.virtualenvs/jsonrpcclient/lib/python3.6/site-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/Users/beau/.virtualenvs/jsonrpcclient/lib/python3.6/site-packages/requests/adapters.py", line 407, in send
    self.cert_verify(conn, request.url, verify, cert)
  File "/Users/beau/.virtualenvs/jsonrpcclient/lib/python3.6/site-packages/requests/adapters.py", line 248, in cert_verify
    "invalid path: {0}".format(conn.cert_file))
OSError: Could not find the TLS certificate file, invalid path: nonexistant
>>> client.send(Request('ping'))
--> {"jsonrpc": "2.0", "method": "ping", "id": 4}
<-- {"jsonrpc": "2.0", "result": "pong", "id": 4} (200 OK)
'pong'
>>>
```

**Comment by luzik** [comment]
Now is OK
