### ISSUE TITLE
http error codes handing 4XX

### ISSUE THREAD

**Issue by luzik** [bcb/jsonrpcclient#67]
When i use bad client cert (cert param) I got just jsonrpcclient.exceptions.ParseResponseError

But there is '400 Bad Request' http status

Inside json.decoder.JSONDecodeError catch there should be status code handling and raise exception based on status codes or just simple raise HttpResponseError(error_code)

**Comment by luzik** [comment]
request just gives you answer with http code and html , do not raise an exception ..test if with 404 running
client = HTTPClient('https://192.168.40.165/non_extisting_url')
client.request('cat')


client.request('cat')
--> {"jsonrpc": "2.0", "method": "cat", "id": 8}
 (400 Bad Request)1.9.5</center>ate was sent</center></title></head>
Traceback (most recent call last):
  File "/home/luzik/.local/lib/python3.5/site-packages/jsonrpcclient/client.py", line 98, in process_response
    response = json.loads(response)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/luzik/.local/lib/python3.5/site-packages/jsonrpcclient/client.py", line 200, in request
    return self.send(Request(method_name, *args, **kwargs))
  File "/home/luzik/.local/lib/python3.5/site-packages/jsonrpcclient/client.py", line 171, in send
    return self.send_message(request, **kwargs)
  File "/home/luzik/.local/lib/python3.5/site-packages/jsonrpcclient/http_client.py", line 76, in send_message
    log_format='<-- %(message)s (%(http_code)s %(http_reason)s)')
  File "/home/luzik/.local/lib/python3.5/site-packages/jsonrpcclient/client.py", line 100, in process_response
    raise exceptions.ParseResponseError()
jsonrpcclient.exceptions.ParseResponseError: The response was not valid JSON

**Comment by bcb** [comment]
The server shouldn't return html.

In that case the ParseResponseError is correct.

**Comment by luzik** [comment]
This is quite normal that server returns html

https://github.com/dupablada17

**Comment by bcb** [comment]
There's no html response in the json-rpc spec.
http://www.jsonrpc.org/specification

JSON only.

**Comment by luzik** [comment]
Because this is another layer issue!
When there is connection problem, exception is handled by underlaying software, the same with ssl verification and lot of others problem on underlaying layers too, but for "requests" dealing with http error codes is something natural - they do not raises exception on this - you have to handle them itself !
jsonrpc do not describes them because this is not theirs layer ..you can use it for example over web sockets

**Comment by luzik** [comment]
check https://github.com/gciotta/jsonrpc-requests/blob/master/jsonrpc_requests/jsonrpc.py:57 or others jsonrpc libs

**Comment by bcb** [comment]
Getting a 404 on your last two links @luzik, can you paste them again?

**Comment by luzik** [comment]
sorry just remove :57
https://github.com/gciotta/jsonrpc-requests/blob/master/jsonrpc_requests/jsonrpc.py line 57

**Comment by luzik** [comment]
and https://github.com/dupablada17 it is just example that running:
jsonrpcclient.request('https://github.com/dupablada17', 'speak') 404 error should be handled by jsonrpcclient

**Comment by bcb** [comment]
We can add this as a configuration option, disabled by default because it's a breaking change for users not expecting this behaviour.
